services:
  postgres:
    image: 'postgres:17'
    container_name: mpaz-postgres
    environment:
      - 'POSTGRES_DB=mpaz'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=mpaz'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U mpaz -d mpaz' ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
