-- =====================================================================
-- MPAZ PRO 6 - Esquema definitivo
-- Fuente: especificaciones/mpaz_pro_modelo_definitivo.md
--   seccion 2 = enums (8)      seccion 3 = tablas (17)
--   seccion 4 = FK compuestas (7)
--   seccion 6 = CHECK e indice parcial
--   seccion 7 = indices de consulta
--   seccion 10 = orden de creacion
--
-- Convenciones de la seccion 1:
--   - Todos los id son bigint autogenerado (identity)
--   - Los enums son varchar + CHECK, nunca el tipo ENUM nativo
--   - Los textos son own: no se copia texto escolar
-- =====================================================================

-- ---------------------------------------------------------------------
-- A) Usuarios  (seccion 10, orden 1)
-- ---------------------------------------------------------------------

CREATE TABLE curso (
    id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(50) NOT NULL,
    anio   integer    NOT NULL
);

CREATE TABLE usuario (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        varchar(150) NOT NULL,
    username      varchar(100) NOT NULL,
    password_hash varchar(255) NOT NULL,
    rol           varchar(20)  NOT NULL,
    curso_id      bigint,
    CONSTRAINT uk_usuario_username UNIQUE (username),
    CONSTRAINT ck_usuario_rol
        CHECK (rol IN ('UTP', 'DOCENTE', 'ESTUDIANTE')),
    -- Regla 1 de la seccion 8: curso_id es exclusivo de los estudiantes.
    CONSTRAINT ck_usuario_curso_solo_estudiante
        CHECK ((rol = 'ESTUDIANTE') = (curso_id IS NOT NULL)),
    CONSTRAINT fk_usuario_curso
        FOREIGN KEY (curso_id) REFERENCES curso (id)
);

-- ---------------------------------------------------------------------
-- B) Catalogo curricular  (orden 3)
-- ---------------------------------------------------------------------

CREATE TABLE asignatura (
    id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(100) NOT NULL,
    CONSTRAINT uk_asignatura_nombre UNIQUE (nombre)
);

CREATE TABLE unidad (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asignatura_id     bigint      NOT NULL,
    nivel_educativo   varchar(50) NOT NULL DEFAULT 'Sexto Basico',
    titulo            varchar(200) NOT NULL,
    orden             integer     NOT NULL DEFAULT 1,
    estado            varchar(20) NOT NULL DEFAULT 'BORRADOR',
    autorizada_por_id bigint,
    fecha_autorizacion timestamp,
    CONSTRAINT ck_unidad_estado
        CHECK (estado IN ('BORRADOR', 'EN_REVISION', 'AUTORIZADO', 'PUBLICADO')),
    CONSTRAINT ck_unidad_orden CHECK (orden > 0),
    -- Seccion 6: autorizada y con fecha si el estado lo exige.
    CONSTRAINT ck_unidad_autorizacion
        CHECK (estado NOT IN ('AUTORIZADO', 'PUBLICADO')
               OR (autorizada_por_id IS NOT NULL AND fecha_autorizacion IS NOT NULL)),
    CONSTRAINT fk_unidad_asignatura
        FOREIGN KEY (asignatura_id) REFERENCES asignatura (id),
    CONSTRAINT fk_unidad_autorizada_por
        FOREIGN KEY (autorizada_por_id) REFERENCES usuario (id)
);

CREATE TABLE objetivo_aprendizaje (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unidad_id        bigint      NOT NULL,
    codigo           varchar(50),
    descripcion      text        NOT NULL,
    eje              varchar(100) NOT NULL,
    texto_referencia varchar(500),
    -- (id, unidad_id) existe para sostener las FK compuestas de la seccion 4.
    CONSTRAINT uk_oa_id_unidad UNIQUE (id, unidad_id),
    CONSTRAINT uk_oa_unidad_codigo UNIQUE (unidad_id, codigo),
    CONSTRAINT fk_oa_unidad
        FOREIGN KEY (unidad_id) REFERENCES unidad (id)
);

CREATE TABLE contenido (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oa_id         bigint       NOT NULL,
    titulo        varchar(200) NOT NULL,
    explicacion   text         NOT NULL,
    ejemplos       text,
    instrucciones text,
    orden         integer      NOT NULL DEFAULT 1,
    origen        varchar(20)  NOT NULL,
    CONSTRAINT ck_contenido_orden CHECK (orden > 0),
    CONSTRAINT ck_contenido_origen
        CHECK (origen IN ('PROPIO', 'PUBLICO', 'AUTORIZADO')),
    CONSTRAINT fk_contenido_oa
        FOREIGN KEY (oa_id) REFERENCES objetivo_aprendizaje (id)
);

CREATE TABLE recurso_contenido (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contenido_id bigint       NOT NULL,
    tipo        varchar(20)  NOT NULL,
    url         varchar(500) NOT NULL,
    descripcion varchar(500),
    origen      varchar(20)  NOT NULL,
    CONSTRAINT ck_recurso_tipo
        CHECK (tipo IN ('IMAGEN', 'AUDIO')),
    CONSTRAINT ck_recurso_origen
        CHECK (origen IN ('PROPIO', 'PUBLICO', 'AUTORIZADO')),
    CONSTRAINT fk_recurso_contenido
        FOREIGN KEY (contenido_id) REFERENCES contenido (id)
);

CREATE TABLE actividad (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unidad_id bigint       NOT NULL,
    titulo    varchar(200) NOT NULL,
    tipo      varchar(20)  NOT NULL,
    orden     integer      NOT NULL DEFAULT 1,
    -- (id, unidad_id) existe para sostener las FK compuestas de la seccion 4.
    CONSTRAINT uk_actividad_id_unidad UNIQUE (id, unidad_id),
    CONSTRAINT ck_actividad_tipo
        CHECK (tipo IN ('ACTIVIDAD', 'DESAFIO', 'PRUEBA_FINAL')),
    CONSTRAINT ck_actividad_orden CHECK (orden > 0),
    CONSTRAINT fk_actividad_unidad
        FOREIGN KEY (unidad_id) REFERENCES unidad (id)
);

CREATE TABLE pregunta (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actividad_id      bigint      NOT NULL,
    unidad_id         bigint      NOT NULL,
    oa_id             bigint      NOT NULL,
    enunciado         text        NOT NULL,
    criterio_respuesta text,
    dificultad        varchar(20) NOT NULL,
    orden             integer     NOT NULL DEFAULT 1,
    CONSTRAINT ck_pregunta_dificultad
        CHECK (dificultad IN ('BAJA', 'MEDIA', 'ALTA')),
    CONSTRAINT ck_pregunta_orden CHECK (orden > 0),
    CONSTRAINT fk_pregunta_actividad
        FOREIGN KEY (actividad_id) REFERENCES actividad (id),
    CONSTRAINT fk_pregunta_unidad
        FOREIGN KEY (unidad_id) REFERENCES unidad (id),
    CONSTRAINT fk_pregunta_oa
        FOREIGN KEY (oa_id) REFERENCES objetivo_aprendizaje (id)
);

CREATE TABLE alternativa (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pregunta_id bigint      NOT NULL,
    texto       varchar(500) NOT NULL,
    es_correcta boolean     NOT NULL DEFAULT false,
    -- (pregunta_id, id) existe para la FK compuesta de la seccion 4.
    CONSTRAINT uk_alternativa_pregunta_id UNIQUE (pregunta_id, id),
    CONSTRAINT fk_alternativa_pregunta
        FOREIGN KEY (pregunta_id) REFERENCES pregunta (id)
);

-- ---------------------------------------------------------------------
-- C) Control del docente  (orden 6)
-- ---------------------------------------------------------------------

CREATE TABLE asignacion (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id     bigint      NOT NULL,
    unidad_id    bigint      NOT NULL,
    docente_id   bigint      NOT NULL,
    -- Nulo = prueba final no habilitada.
    max_intentos integer,
    fecha        timestamp   NOT NULL,
    CONSTRAINT uk_asignacion_curso_unidad UNIQUE (curso_id, unidad_id),
    -- (id, unidad_id) existe para sostener las FK compuestas de la seccion 4.
    CONSTRAINT uk_asignacion_id_unidad UNIQUE (id, unidad_id),
    CONSTRAINT ck_asignacion_max_intentos
        CHECK (max_intentos IS NULL OR max_intentos > 0),
    CONSTRAINT fk_asignacion_curso
        FOREIGN KEY (curso_id) REFERENCES curso (id),
    CONSTRAINT fk_asignacion_unidad
        FOREIGN KEY (unidad_id) REFERENCES unidad (id),
    CONSTRAINT fk_asignacion_docente
        FOREIGN KEY (docente_id) REFERENCES usuario (id)
);

-- PK compuesta unica de dos columnas (seccion 3).
CREATE TABLE asignacion_oa (
    asignacion_id bigint NOT NULL,
    unidad_id     bigint NOT NULL,
    oa_id         bigint NOT NULL,
    CONSTRAINT pk_asignacion_oa PRIMARY KEY (asignacion_id, oa_id),
    CONSTRAINT fk_asignacion_oa_asignacion
        FOREIGN KEY (asignacion_id) REFERENCES asignacion (id),
    CONSTRAINT fk_asignacion_oa_unidad
        FOREIGN KEY (unidad_id) REFERENCES unidad (id),
    CONSTRAINT fk_asignacion_oa_oa
        FOREIGN KEY (oa_id) REFERENCES objetivo_aprendizaje (id)
);

CREATE TABLE asignacion_actividad (
    asignacion_id bigint NOT NULL,
    unidad_id     bigint NOT NULL,
    actividad_id  bigint NOT NULL,
    CONSTRAINT pk_asignacion_actividad PRIMARY KEY (asignacion_id, actividad_id),
    CONSTRAINT fk_asignacion_actividad_asignacion
        FOREIGN KEY (asignacion_id) REFERENCES asignacion (id),
    CONSTRAINT fk_asignacion_actividad_unidad
        FOREIGN KEY (unidad_id) REFERENCES unidad (id),
    CONSTRAINT fk_asignacion_actividad_actividad
        FOREIGN KEY (actividad_id) REFERENCES actividad (id)
);

-- ---------------------------------------------------------------------
-- D) Actividad del estudiante  (orden 7)
-- ---------------------------------------------------------------------

CREATE TABLE intento (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id bigint      NOT NULL,
    actividad_id  bigint      NOT NULL,
    numero        integer     NOT NULL,
    fecha_inicio  timestamp   NOT NULL,
    fecha_fin     timestamp,
    CONSTRAINT uk_intento_estudiante_actividad_numero
        UNIQUE (estudiante_id, actividad_id, numero),
    CONSTRAINT ck_intento_numero CHECK (numero > 0),
    -- Seccion 6: no se puede terminar antes de empezar.
    CONSTRAINT ck_intento_fechas
        CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio),
    CONSTRAINT fk_intento_estudiante
        FOREIGN KEY (estudiante_id) REFERENCES usuario (id),
    CONSTRAINT fk_intento_actividad
        FOREIGN KEY (actividad_id) REFERENCES actividad (id)
);

CREATE TABLE respuesta_estudiante (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intento_id    bigint  NOT NULL,
    pregunta_id   bigint  NOT NULL,
    alternativa_id bigint NOT NULL,
    -- Derivado y guardado a proposito: congela el resultado (seccion 5).
    es_correcta   boolean NOT NULL,
    CONSTRAINT uk_respuesta_intento_pregunta UNIQUE (intento_id, pregunta_id),
    CONSTRAINT fk_respuesta_intento
        FOREIGN KEY (intento_id) REFERENCES intento (id),
    CONSTRAINT fk_respuesta_pregunta
        FOREIGN KEY (pregunta_id) REFERENCES pregunta (id),
    CONSTRAINT fk_respuesta_alternativa
        FOREIGN KEY (alternativa_id) REFERENCES alternativa (id)
);

-- ---------------------------------------------------------------------
-- E) Informe  (orden 8)
-- ---------------------------------------------------------------------

CREATE TABLE informe_pedagogico (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id    bigint      NOT NULL,
    unidad_id        bigint      NOT NULL,
    docente_id       bigint      NOT NULL,
    fecha_generacion timestamp   NOT NULL,
    estado           varchar(30) NOT NULL DEFAULT 'GENERADO',
    fecha_validacion timestamp,
    CONSTRAINT ck_informe_estado
        CHECK (estado IN ('GENERADO', 'PENDIENTE_VALIDACION', 'VALIDADO')),
    -- Seccion 6: VALIDADO y fecha_validacion van siempre juntos.
    CONSTRAINT ck_informe_validacion
        CHECK ((estado = 'VALIDADO') = (fecha_validacion IS NOT NULL)),
    CONSTRAINT fk_informe_estudiante
        FOREIGN KEY (estudiante_id) REFERENCES usuario (id),
    CONSTRAINT fk_informe_unidad
        FOREIGN KEY (unidad_id) REFERENCES unidad (id),
    CONSTRAINT fk_informe_docente
        FOREIGN KEY (docente_id) REFERENCES usuario (id)
);

CREATE TABLE detalle_informe_oa (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    informe_id      bigint      NOT NULL,
    oa_id           bigint      NOT NULL,
    total_preguntas integer     NOT NULL,
    correctas       integer     NOT NULL,
    nivel           varchar(20) NOT NULL,
    CONSTRAINT uk_detalle_informe_oa UNIQUE (informe_id, oa_id),
    CONSTRAINT ck_detalle_nivel
        CHECK (nivel IN ('FORTALEZA', 'REFUERZO')),
    -- Seccion 6: correctas no puede superar el total.
    CONSTRAINT ck_detalle_correctas
        CHECK (correctas >= 0 AND total_preguntas >= 0 AND correctas <= total_preguntas),
    CONSTRAINT fk_detalle_informe
        FOREIGN KEY (informe_id) REFERENCES informe_pedagogico (id),
    CONSTRAINT fk_detalle_oa
        FOREIGN KEY (oa_id) REFERENCES objetivo_aprendizaje (id)
);

-- =====================================================================
-- Seccion 4: FK compuestas (7)
-- Cada una impide que una fila apunte a una entidad de otra unidad.
-- =====================================================================

-- Evita una pregunta cuya unidad no sea la de su actividad.
ALTER TABLE pregunta
    ADD CONSTRAINT fk_pregunta_actividad_unidad
        FOREIGN KEY (actividad_id, unidad_id)
        REFERENCES actividad (id, unidad_id);

-- Evita una pregunta con un OA de otra unidad.
ALTER TABLE pregunta
    ADD CONSTRAINT fk_pregunta_oa_unidad
        FOREIGN KEY (oa_id, unidad_id)
        REFERENCES objetivo_aprendizaje (id, unidad_id);

-- Evita un OA asignado en otra unidad.
ALTER TABLE asignacion_oa
    ADD CONSTRAINT fk_asignacion_oa_asignacion_unidad
        FOREIGN KEY (asignacion_id, unidad_id)
        REFERENCES asignacion (id, unidad_id);

ALTER TABLE asignacion_oa
    ADD CONSTRAINT fk_asignacion_oa_oa_unidad
        FOREIGN KEY (oa_id, unidad_id)
        REFERENCES objetivo_aprendizaje (id, unidad_id);

-- Evita una actividad asignada en otra unidad.
ALTER TABLE asignacion_actividad
    ADD CONSTRAINT fk_asignacion_actividad_asignacion_unidad
        FOREIGN KEY (asignacion_id, unidad_id)
        REFERENCES asignacion (id, unidad_id);

ALTER TABLE asignacion_actividad
    ADD CONSTRAINT fk_asignacion_actividad_actividad_unidad
        FOREIGN KEY (actividad_id, unidad_id)
        REFERENCES actividad (id, unidad_id);

-- Evita responder una alternativa que pertenece a otra pregunta.
ALTER TABLE respuesta_estudiante
    ADD CONSTRAINT fk_respuesta_alternativa_pregunta
        FOREIGN KEY (pregunta_id, alternativa_id)
        REFERENCES alternativa (pregunta_id, id);

-- =====================================================================
-- Seccion 6: una sola prueba final por unidad
-- =====================================================================

CREATE UNIQUE INDEX ux_actividad_prueba_final_por_unidad
    ON actividad (unidad_id)
    WHERE tipo = 'PRUEBA_FINAL';

-- =====================================================================
-- Seccion 7: indices de consulta
-- PostgreSQL no indexa automaticamente las claves foraneas.
-- =====================================================================

CREATE INDEX ix_actividad_unidad
    ON actividad (unidad_id);

CREATE INDEX ix_contenido_oa
    ON contenido (oa_id);

CREATE INDEX ix_pregunta_actividad
    ON pregunta (actividad_id);

CREATE INDEX ix_pregunta_oa
    ON pregunta (oa_id);

CREATE INDEX ix_respuesta_pregunta
    ON respuesta_estudiante (pregunta_id);

CREATE INDEX ix_informe_estudiante_unidad
    ON informe_pedagogico (estudiante_id, unidad_id);

-- Reglas de la seccion 8 que la BD si puede expresar:
--   1. Solo los estudiantes tienen curso_id  -> ck_usuario_curso_solo_estudiante
--   6. (validado <-> fecha_validacion)      -> ck_informe_validacion
-- Las demas (rol del docente, del UTP, pertenencia de la pregunta a la
-- actividad del intento, OAs del informe dentro de la unidad) las valida
-- el Service; ver seccion 8, items 1, 2, 9 y 11.
